### ISSUE TITLE
Improve UX when passing a realm address

### ISSUE THREAD

**Issue by moul** [onbloc/gnoscan#82]
https://gnoscan.io/accounts/g1ttrq7mp4zy6dssnmgyyktnn4hcj3ys8xhju0n7 is the pkg address of [`r/gnoland/faucet`](https://gnoscan.io/realms/details?path=gno.land%2Fr%2Fgnoland%2Ffaucet).

It would be nice if Gnoscan could detect it so we arrive directly on the realm UI.

And then, make sure that you can display contracts' balance.

**Comment by r3v4s** [comment]
Hey @moul thx for your comment.
Just to be sure
`And then, make sure that you can display contracts' balance.`
Do you mean by displaying contract's (gnot) balance on [r/gnoland/faucet](https://gnoscan.io/realms/details?path=gno.land%2Fr%2Fgnoland%2Ffaucet) page?

**Comment by dongwon8247** [comment]
@moul Hey, this [release](https://github.com/onbloc/gnoscan/releases/tag/v0.3.5) solved your issue.

- We've added `Realm Address` and `Balance` in the Realm UI ([Link](https://gnoscan.io/realms/details?path=gno.land/r/gnoland/faucet)).  
- In the Search, we detect if it's an address or a realm address and direct to the Realm UI if it's a realm address. Also, if you search in the below ways, it also directs to the Realm UI.
	- https://gnoscan.io/accounts/g1ttrq7mp4zy6dssnmgyyktnn4hcj3ys8xhju0n7
	- https://gnoscan.io/realms/g1ttrq7mp4zy6dssnmgyyktnn4hcj3ys8xhju0n7
	- https://gnoscan.io/realms/details?path=g1ttrq7mp4zy6dssnmgyyktnn4hcj3ys8xhju0n7
	
One issue we found during this work is that we need to find a way to strongly discourage sending tokens to realm addresses for users. Since the form of user addresses and realm addresses are the same (indistinguishable), it could be confusing for users and it's possible they could mistakenly send tokens to realm addresses. In this case, if the realm doesn't support a transfer function (which will be most likely), it's lost forever, like Ethereum's case. We'll work on improving this UI/UX for users.

Thank you for making this issue.
